# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Create and publish a Docker image

on:
  workflow_dispatch:
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  RawDataDirectory: ${{ github.workspace}}/raw
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dump-csv:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file-name:
          - LCA_Disclosure_Data_FY2021_Q1
          - LCA_Disclosure_Data_FY2021_Q2
          - LCA_Disclosure_Data_FY2021_Q3
          - LCA_Disclosure_Data_FY2021_Q4
          - LCA_Disclosure_Data_FY2022_Q1
          - LCA_Disclosure_Data_FY2022_Q2
          - LCA_Disclosure_Data_FY2022_Q3
          - LCA_Disclosure_Data_FY2022_Q4
          - LCA_Disclosure_Data_FY2023_Q1
    steps:
      - uses: actions/checkout@v3
      - name: Download excel file
        run: wget https://www.dol.gov/sites/dolgov/files/ETA/oflc/pdfs/${{ matrix.file-name }}.xlsx
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
      - name: Install xlsx2csv
        run: dotnet tool update xlsx2csv --global
      - name: Convert to csv
        run: xlsx2csv ${{ matrix.file-name }}.xlsx
      - name: Setup python sqlite-utils
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install sqlite-utils
      - run: sqlite-utils insert ${{ matrix.file-name }}.db ${{ matrix.file-name }} ${{ matrix.file-name }}.csv --csv
      - name: Upload artifacts 
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file-name }}
          if-no-files-found: error
          path: ${{ github.workspace}}/*.db
          retention-days: 1
  process-csv-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: dump-csv
    if: success()
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: csv_dumps
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: csv_dumps
      
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

